# Generated by Django 5.0.7 on 2024-07-26 16:23

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('user_id', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('displayname', models.CharField(max_length=20, unique=True)),
                ('online', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
