# Generated by Django 5.0.6 on 2024-07-03 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="online_status",
            new_name="online",
        ),
    ]
