# Generated by Django 5.0.6 on 2024-07-19 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_friendrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MatchRecord',
        ),
    ]
