# Configuration file for MegaLinter
#
# See all available variables at https://megalinter.io/latest/config-file/ and in
# linters documentation

APPLY_FIXES: all

ENABLE: [CSS, JSON, YAML, JAVASCRIPT, HTML]

EXCLUDED_DIRECTORIES:
  - .github
  - linterrules

LOG_LEVEL: INFO

JAVASCRIPT_DEFAULT_STYLE: prettier

#DISABLE_ERRORS_LINTERS:
#  - JAVASCRIPT_PRETTIER
#  - JAVASCRIPT_ES
#  - HTML_DJLINT

JAVASCRIPT_ES_CONFIG_FILE: linterrules/eslint.config.js

GITHUB_STATUS_REPORTER: true

SHOW_ELAPSED_TIME: true

LINTER_RULES_PATH: linterrules

FILEIO_REPORTER: false

# if you want MegaLinter to detect errors but not block CI to pass
DISABLE_ERRORS: false
