services:
  database:
    # image to fetch from docker hub
    image: postgres:16
    # Environment variables for startup script
    # container will use these variables
    # to start the container with these define variables.
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    expose:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 4

  #web:
  #  build: ./srcs
  #  command: scripts/entrypoint.sh
  #  volumes:
  #    - ./srcs:/transcendence
  #  expose:
  #    - "8000:8000"
  #  depends_on:
  #    database:
  #      condition: service_healthy
  #  env_file:
  #    - .env

  #nginx:
  #  build: ./nginx
  #  ports:
  #    - 8080:443
  #  depends_on:
  #    - web
  #    - database

volumes:
  postgres_data:
