#!/bin/bash

echo "CREATE USER $POSTGRES_ACCESS_USER WITH ENCRYPTED PASSWORD '$POSTGRES_ACCESS_PASSWORD';" >> init.sql
echo "GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB TO $POSTGRES_ACCESS_USER;" >> init.sql
