POST {{base_url}}/registration/basic_login
Content-Type: application/json

{
	"username": "a@a.at",
	"password": "a"
}

###

# @name login
POST {{base_url}}/registration/basic_login
Content-Type: application/json

{
	"username": "a@a.at",
	"password": "a",
	"otp": "0000000000000000"
}

###

@ACCESS_COOKIE = {{login.response.headers.Set-Cookie}};

###

GET {{base_url}}/game/get_game_stats
Content-Type: application/json
Cookie: {{ACCESS_COOKIE}}

{
}