@base_url = https://localhost:8000

###

POST {{base_url}}/registration/signup/
Content-Type: application/json
Cookie: access=wrongvalue

{"username": "email@domain.at", "password": "Pass1234!"}

###

# @name post_signup
POST {{base_url}}/registration/signup/
Content-Type: application/json

{"username": "email@domain.at", "password": "Pass1234!"}

###

POST {{base_url}}/registration/login/
Content-Type: application/json
Cookie: access=wrongvalue

{"username": "email@domain.at", "password": "Pass1234!"}

