@base_url = https://localhost:8000

# @name post_signup
POST {{base_url}}/registration/signup/
Content-Type: application/json

{"username": "email@domain.at", "password": "Pass1234!"}

###

# @name post_login
POST {{base_url}}/registration/login/
Content-Type: application/json

{"username": "email@domain.at", "password": "Pass1234!"}

###

@SET_COOKIE = {{post_login.response.headers.Set-Cookie}}

###

@ACCESS_COOKIE = {{SET_COOKIE}}


POST {{base_url}}/registration/delete_user/
Content-Type: application/json
Cookie: {{ACCESS_COOKIE}}

{"current_password": "Pass1234!"}

###

GET {{base_url}}/registration/logout/
Content-Type: application/json
Cookie: {{ACCESS_COOKIE}}

{}

###

POST {{base_url}}/registration/change_password/
Content-Type: application/json
Cookie: {{ACCESS_COOKIE}}

{"current_password": "Pass1234!", "new_password": "Pass5678!"}

###

GET {{base_url}}/registration/verify_token/
Content-Type: application/json
Cookie: {{ACCESS_COOKIE}}

{}

###

POST {{base_url}}/registration/forgot_password/
Content-Type: application/json

{"email": "email@domain.at"}

###

GET {{base_url}}/registration/refresh_token/
Content-Type: application/json
Cookie: refresh=x.x.x;y;z

{}
