@base_url = https://localhost:8000
@username = user@domain.at
@current_password = Pass1234!
@new_password = Yo?4567


# @name post_signup
POST {{base_url}}/registration/signup/
Content-Type: application/json

{
    "username": "{{username}}",
    "password": "{{current_password}}"
}

###

# @name post_login
POST {{base_url}}/registration/login/
Content-Type: application/json

{
    "username": "{{username}}",
    "password": "{{current_password}}"
}

###

@ACCESS_COOKIE = {{post_login.response.headers.Set-Cookie}};

###


POST {{base_url}}/registration/delete_user/
Content-Type: application/json
Cookie: {{ACCESS_COOKIE}} 

{"password": "{{current_password}}"}

###

GET {{base_url}}/registration/logout/
Content-Type: application/json
Cookie: {{ACCESS_COOKIE}}

{}

###

POST {{base_url}}/registration/change_password/
Content-Type: application/json
Cookie: {{ACCESS_COOKIE}}

{"current_password": "{{current_password}}", "new_password": "{{new_password}}"}

###

GET {{base_url}}/registration/verify_token/
Content-Type: application/json
Cookie: {{ACCESS_COOKIE}} 

{}

###

POST {{base_url}}/registration/forgot_password/
Content-Type: application/json

{
    "username": "{{username}}"
}

###

POST {{base_url}}/registration/forgot_password_reset/
Content-Type: application/json

{
    "username": "{{username}}",
    "token": "xxxxxxxxxxxxxxxxxx",
    "new_password": "New#789!"
}

###

GET {{base_url}}/registration/refresh_token/
Content-Type: application/json
Cookie: REFRESH_COOKIE

{}
