
@baseUrl = https://localhost:8000

POST {{baseUrl}}/registration/basic_signup
Content-Type: application/json

{
    "username": "email@domain.at",
    "password": "Pass1234!"
}

###

# @name postSignup
POST {{baseUrl}}/registration/basic_signup
Content-Type: application/json

{
    "username": "email@domain.at",
    "password": "Pass1234!",
    "otp": "0000000000000000"
}

###


POST {{baseUrl}}/registration/basic_login
Content-Type: application/json

{
    "username": "email@domain.at",
    "password": "Pass1234!"
}

###

# @name postLogin
POST {{baseUrl}}/registration/basic_login
Content-Type: application/json

{
    "username": "email@domain.at",
    "password": "Pass1234!",
    "otp": "0000000000000000"
}

###

@cookie = {{postLogin.response.headers.Set-Cookie}}

###

@displayname = ProCoder
POST {{baseUrl}}/um/user-creation
Content-Type: application/json
Cookie: {{cookie}}

{
    "displayname": "{{displayname}}"
}


###

GET {{baseUrl}}/um/profile/{{displayname}}
Content-Type: application/json
Cookie: {{cookie}}


###

GET {{baseUrl}}/um/search?term=Mario
Content-Type: application/json
Cookie: {{cookie}}

###

GET {{baseUrl}}/um/friends/
Content-Type: application/json
Cookie: {{cookie}}


###

POST {{baseUrl}}/um/friends/send
Content-Type: application/json
Cookie: {{cookie}}

{
    "receiver": "MeMario"
}