POST https://127.0.0.1:8000/um/api/user-creation/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzIyOTUwMjU5LCJpYXQiOjE3MjI5NDk5NTksImp0aSI6IjBiMGQzZjc4YjkxNTRiZGE4OWNhNTBiYWVkN2ZkODMzIiwidXNlcl9pZCI6ImQ5YzJkMTU0LTVlZWYtNDE0MC05ODk3LTI5YzA4MGMzZTg4NSJ9.y70Nq9N3Lj6X9x3WextE5zpMLa9sXt6hoO5P8l2K9aE

{"displayname": "name"}
