POST https://127.0.0.1:8000/um/user-creation/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzIyOTUxODAzLCJpYXQiOjE3MjI5NTE1MDMsImp0aSI6IjU3YzYyYmVjMDg5NDQ4ZmE4ZWJkZTlkYmIyODQzMTY5IiwidXNlcl9pZCI6IjhkYmI0M2JiLTFiNjktNDZiNi04OTRmLWVmNmMzMDM4MTk3MSJ9.E8_cq9Gf6KjftzJi-7quQt3DiB_0JkJ5JBv5S0apw42ZAGjiu5a0pTJvhF64at-NhYsHfxmUJHq5EYtfoKJLW4b_bCUlyjRJm7AWLwMM57uuaJ-Zge_TyfQCTACB4IeXs8ZMnLW3aDLVvKVO7MUQYz7nIJt5X5OfTE3NIspnTsczJnbgF_b9jr1zb6lmEmpCTXUKcS02ZdkXip07Uv1EhSARQL8IsPvoUZCSF7g9Su7XEyGEdsfP6tXUUsEjour6t4Qz7by74DxtQA7b_yEmzjqEBBi-ws091Xb8WmqpgJtWoFgLTnGkzama_WKb7ZU9WwAeSlGR4rAYJsm4zr_Hhw

{"displayname": "name"}
