openapi: 3.0.3
info:
  title: ft_transcendence
  description: |-
    This is the documentation of the API endpoints for the ft_transcendence project created by a team at 42 Vienna.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: '0.1'
servers:
  - url: https://localhost/api/
tags:
  - name: registration
    description: Required for registration/signup and login
  - name: user
    description: Everything related to managing the user
paths:
  /login:
    get:
      tags:
        - registration
      summary: Logs a user in
      description: I'm lazy
      requestBody:
        description: Update an existent pet in the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
          application/xml:
            schema:
              $ref: '#/components/schemas/User'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'          
            application/xml:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Invalid ID supplied
        '404':
          description: Pet not found
        '422':
          description: Validation exception
components:
  schemas:
    User:
      type: object
      properties:
        uid:
          type: string
          format: uuid
        displayname:
          type: string
          minLength: 1
          example: Max Mustermann
        img:
          type: string
          example: "https://i.pravatar.cc/15"
        online:
          type: boolean
        relationship:
          type: string
          description: relationship between users
          example: friend
          enum:
            - friend
            - requested
            - received
            - none