name: pong

include:
    - user_management.yml
    - registration.yml
    - game.yml

services:

  nginx:
    container_name: pong_nginx
    build: ../src/nginx
    volumes: # [aguilmea]  this has to be deleted once dev is ready
      - ../src/nginx/static:/www/data
    ports:
      - 8000:443
    depends_on:
      - registration
      - usermanagement
      - game
    networks:
      - network_game
      - network_user_management
      - network_registration
      - network_django
    secrets:
      - localhost.crt
      - localhost.key
    profiles:
      - all
    restart: on-failure

volumes:
  volume_game:
  volume_registration:
  volume_user_management:

networks:
  network_game:
    driver: bridge
  network_redis_game:
    driver: bridge
  network_registration:
    driver: bridge
  network_user_management:
    driver: bridge
  network_django:
    driver: bridge

secrets:
  public_key.pem:
    file: ../src/common_files/jwt_keys/public_key.pem
  private_key.pem:
    file: ../src/common_files/jwt_keys/private_key.pem
  localhost.crt:
    file: ../src/common_files/ssl_certs/localhost.crt
  localhost.key:
    file: ../src/common_files/ssl_certs/localhost.key