name: pong

include:
    - user_management.yml
    - registration.yml
    - game.yml

services:
  nginx:
    container_name: pong_nginx
    build: ../src/nginx
    volumes: # [aguilmea]  this has to be deleted once dev is ready
      - ../src/nginx/static:/usr/share/nginx/html
    environment:
      - DOMAIN=${DOMAIN:-localhost}
      - SSL_PORT=${SSL_PORT:-8443}
      - PLAIN_PORT=${PLAIN_PORT:-8080}
    ports:
      - ${PLAIN_PORT:-8080}:80
      - ${SSL_PORT:-8443}:443
    depends_on:
      - registration
      - usermanagement
      - game
    networks:
      - network_game
      - network_user_management
      - network_registration
      - network_django
    secrets:
      - source: ssl_webpage.crt
        target: /run/secrets/${DOMAIN:-localhost}.crt
      - source: ssl_webpage.key
        target: /run/secrets/${DOMAIN:-localhost}.key
    restart: on-failure

volumes:
  volume_game:
  volume_registration:
  volume_user_management:

networks:
  network_game:
    driver: bridge
  network_redis_game:
    driver: bridge
  network_registration:
    driver: bridge
  network_user_management:
    driver: bridge
  network_redis_um:
    driver: bridge
  network_django:
    driver: bridge

secrets:
  public_key.pem:
    file: ../src/common_files/jwt_keys/public_key.pem
  private_key.pem:
    file: ../src/common_files/jwt_keys/private_key.pem
  ssl_webpage.crt:
    file: ../src/common_files/ssl_certs/ssl_webpage.crt
  ssl_webpage.key:
    file: ../src/common_files/ssl_certs/ssl_webpage.key