services:
  db_game:
    container_name: pong_game_db
    build: ../src/common_files/postgres
    environment:
      POSTGRES_DB: "${GAME_POSTGRES_DB:-default_db}"
      POSTGRES_USER: "${GAME_POSTGRES_USER:-admin}"
      POSTGRES_PASSWORD:  "${GAME_POSTGRES_PASSWORD:-adminpass}"
      POSTGRES_ACCESS_USER: "${GAME_POSTGRES_ACCESS_USER:-game_accessy}"
      POSTGRES_ACCESS_PASSWORD: "${GAME_POSTGRES_ACCESS_PASSWORD:-accesspass}"
      POSTGRES_INITDB_ARGS: "-A scram-sha-256"
    expose:
      - 5432
    volumes:
      - volume_game:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${GAME_POSTGRES_ACCESS_USER:-game_accessy} -d ${GAME_POSTGRES_DB:-default_db}"]
      interval: 10s
      timeout: 5s
      retries: 4
    restart: on-failure
    networks:
      - network_game

  redis_game:
    container_name: pong_game_redis
    build: ../src/common_files/redis
    environment:
      REDIS_USER: "${GAME_REDIS_USER:-redisuser}"
      REDIS_PASSWORD: "${GAME_REDIS_PASSWORD:-redispass}"
    expose:
      - 6379
    healthcheck:
      test: [ "CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 2s
      retries: 4
    networks:
      - network_redis_game

  game:
    container_name: pong_game
    build: ../src/game
    expose:
      - "8000/tcp"
    environment:
      SERVER_URL: ${SERVER_URL:-https://localhost:8443}
      DOMAIN: ${DOMAIN:-localhost}
      DEBUG: "${DEBUG:-False}"

      DJ_SECRET_KEY: ${SECRET_KEY_GAME:-%-@gf6yxu&v^e%bw-@b@#c@!w@8s74#%-@gf6yxu&@4p-!5$)&wuv^e%bw-y#qm(3!(}
      
      DB_HOST: "db_game"
      POSTGRES_DB: "${GAME_POSTGRES_DB:-default_db}"
      POSTGRES_ACCESS_USER: "${GAME_POSTGRES_ACCESS_USER:-game_accessy}"
      POSTGRES_ACCESS_PASSWORD: "${GAME_POSTGRES_ACCESS_PASSWORD:-accesspass}"

      REDIS_USER: "${GAME_REDIS_USER:-redisuser}"
      REDIS_PASSWORD: "${GAME_REDIS_PASSWORD:-redispass}"

      PYTHONUNBUFFERED: 1
      DJ_SUDO_USERNAME: "${GAME_DJ_SUDO_USERNAME:-admin}"
      DJ_SUDO_EMAIL: "${GAME_DJ_SUDO_EMAIL:-admin@example.com}"
      DJ_SUDO_PASSWORD: "${GAME_DJ_SUDO_PASSWORD:-transcendence}"
    depends_on:
      db_game:
        condition: service_healthy
      redis_game:
        condition: service_healthy
    restart: on-failure
    networks:
      - network_game
      - network_redis_game
      - network_django
    secrets:
      - public_key.pem
