services:

  db_registration:
    container_name: pong_reg_db
    image: postgres:16
    environment:
      POSTGRES_DB: "${POSTGRES_DB_REG:-reg_postgress_db}"
      POSTGRES_USER: "${POSTGRES_USER_REG:-reg_postgress_user}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD_REG:-reg_postgress_password}"
      POSTGRES_ACCESS_USER: "${POSTGRES_ACCESS_USER_REG:-reg_postgress_access_user}"
      POSTGRES_ACCESS_PASSWORD: "${POSTGRES_ACCESS_PASSWORD_REG:-reg_postgress_access_password}"
    expose:
      - "${DB_PORT_REG:-5432}"
    volumes:
      - volume_registration:/var/lib/postgresql/data
      - ../src/common_files/db_init.sh:/docker-entrypoint-initdb.d/init.sh:ro
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER_REG:-reg_postgress_user} -d ${POSTGRES_DB_REG:-reg_postgress_db}"]
      interval: 10s
      timeout: 5s
      retries: 4
    restart: on-failure
    profiles:
      - registration
      - all
    networks:
      - network_registration

  registration:
    container_name: pong_reg
    build: ../src/registration
    volumes:
      - ../src/registration:/app
    expose:
      - "8000/tcp"
    environment:
      POSTGRES_DB: "${POSTGRES_DB_REG:-reg_postgress_db}"
      POSTGRES_ACCESS_USER: "${POSTGRES_USER_REG:-reg_postgress_access_user}"
      POSTGRES_ACCESS_PASSWORD: "${POSTGRES_PASSWORD_REG:-reg_postgress_access_password}"
      DB_HOST: "${DB_HOST_REG:-db_registration}"
      DB_PORT: "${DB_PORT_REG:-5432}"
      SECRET_KEY: ${SECRET_KEY_REG:-random_for_dev_#^0%uiw_5zqca7(sm#(x9nnf*5(kjnk}
      DEBUG: ${DEBUG:-False}
      SILK: "${SILK:-False}"
      MOCK_EMAIL: "${MOCK_EMAIL:-True}" #[aguilmea] to be changed once the variable is set in github for the workflows running automatically
      MOCK_OTP: "${MOCK_OTP:-True}" #[aguilmea] to be changed once the front end check is changed
      SERVER_URL: ${SERVER_URL:-https://localhost:8000}
      DOMAIN: ${DOMAIN:-localhost}
      FT_CLIENT_ID: "${FT_CLIENT_ID:-u-s4t2ud-xxx}"
      FT_CLIENT_SECRET: "${FT_CLIENT_SECRET:-s-s4t2ud-xxx}"
      EMAIL_HOST: "${EMAIL_HOST:-smtp.gmail.com}"
      EMAIL_HOST_USER: "${EMAIL_HOST_USER:-donotuse@gmail.com}"
      EMAIL_HOST_PASSWORD: "${EMAIL_HOST_PASSWORD:-donotuse}"
      SENDGRID_API_KEY: "${SENDGRID_API_KEY:-SG.}"
    depends_on:
      db_registration:
        condition: service_healthy
      redis_registration:
        condition: service_started
    restart: on-failure
    profiles:
      - registration
      - all
    networks:
      - network_registration
      - network_django
    secrets:
      - public_key.pem
      - private_key.pem

  redis_registration:
    container_name: pong_reg_redis
    image: "redis:alpine"
    expose:
        - "6379"
    networks:
      - network_registration
