services:

  db_registration:
    container_name: pong_reg_db
    image: postgres:16
    environment:
      POSTGRES_DB: "${POSTGRES_DB_REG:-reg_postgress_db}"
      POSTGRES_USER: "${POSTGRES_USER_REG:-reg_postgress_user}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD_REG:-reg_postgress_password}"
      POSTGRES_ACCESS_USER: "${POSTGRES_ACCESS_USER_REG:-reg_postgress_access_user}"
      POSTGRES_ACCESS_PASSWORD: "${POSTGRES_ACCESS_PASSWORD_REG:-reg_postgress_access_password}"
    expose:
      - "${DB_PORT_REG:-5432}"
    volumes:
      - volume_registration:/var/lib/postgresql/data
      - ../src/common_files/db_init.sh:/docker-entrypoint-initdb.d/init.sh:ro
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER_REG:-reg_postgress_user} -d ${POSTGRES_DB_REG:-reg_postgress_db}"]
      interval: 10s
      timeout: 5s
      retries: 4
    restart: on-failure
    profiles:
      - registration
      - all
    networks:
      - network_registration

  registration:
    container_name: pong_reg
    build: ../src/registration
    volumes:
      - ../src/registration:/app
    expose:
      - "8000/tcp"
    environment:
      POSTGRES_DB: "${POSTGRES_DB_REG:-reg_postgress_db}"
      POSTGRES_ACCESS_USER: "${POSTGRES_USER_REG:-reg_postgress_access_user}"
      POSTGRES_ACCESS_PASSWORD: "${POSTGRES_PASSWORD_REG:-reg_postgress_access_password}"
      DB_HOST: "${DB_HOST_REG:-db_registration}"
      DB_PORT: "${DB_PORT_REG:-5432}"
      SECRET_KEY: ${SECRET_KEY_REG:-random_for_dev_#^0%uiw_5zqca7(sm#(x9nnf*5(kjnk}
      DEBUG: ${DJANGO_DEBUG_REG:-False}
      SERVER_URL: ${SERVER_URL_REG:-https://localhost:8000}
      FT_CLIENT_ID: "${FT_CLIENT_ID:-u-s4t2ud-xxx}"
      FT_CLIENT_SECRET: "${FT_CLIENT_SECRET:-s-s4t2ud-xxx}"
    depends_on:
      db_registration:
        condition: service_healthy
    restart: on-failure
    profiles:
      - registration
      - all
    networks:
      - network_registration
    secrets:
      - public_key.pem
      - private_key.pem
