services:
  # TODO: change _MANAGEMENT ending to _UM
  db_usermanagement:
    container_name: pong_um_db
    build: ../src/common_files/postgres
    environment:
      POSTGRES_DB: "${UM_POSTGRES_DB:-default_db}"
      POSTGRES_USER: "${UM_POSTGRES_USER:-posty}"
      POSTGRES_PASSWORD: "${UM_POSTGRES_PASSWORD:-insecurepass}"
      POSTGRES_ACCESS_USER: "${UM_POSTGRES_ACCESS_USER:-accessy}"
      POSTGRES_ACCESS_PASSWORD: "${UM_POSTGRES_ACCESS_PASSWORD:-accesspass}"
    expose:
      - 5432
    volumes:
      - volume_user_management:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${UM_POSTGRES_USER:-posty} -d ${UM_POSTGRES_DB:-default_db}"]
      interval: 10s
      timeout: 5s
      retries: 4
    restart: on-failure
    networks:
      - network_user_management

  usermanagement:
    container_name: pong_um
    build: ../src/user_management
    volumes:
      - ../src/user_management:/user_management
    expose:
      - "8000/tcp"
    environment:
      SERVER_URL: ${SERVER_URL:-https://localhost:8443}
      DEBUG: ${DEBUG:-True} # TODO: change to False or set DEBUG in actions to True?

      DJ_SECRET_KEY: ${UM_DJ_SECRET_KEY:-random_for_dev_#^0%uiw_5zqca7(sm#(x9nnf*5(kjnk}
      DJ_ALLOWED_HOSTS: "${UM_DJ_ALLOWED_HOSTS:-localhost}" # TODO: needed?
      DB_HOST: "${UM_DB_HOST:-db_usermanagement}"

      POSTGRES_DB: "${UM_POSTGRES_DB:-default_db}"
      POSTGRES_ACCESS_USER: "${UM_POSTGRES_ACCESS_USER:-accessy}"
      POSTGRES_ACCESS_PASSWORD: "${UM_POSTGRES_ACCESS_PASSWORD:-accesspass}"
      
      # TODO: delete dev vars or keep them but only create admin user if DEBUG = True?
      POSTGRES_USER: "${UM_POSTGRES_USER:-posty}"
      POSTGRES_PASSWORD: "${UM_POSTGRES_PASSWORD:-insecurepass}"

      DJ_SUDO_USERNAME: "${UM_DJ_SUDO_USERNAME:-admin}"
      DJ_SUDO_EMAIL: "${UM_DJ_SUDO_EMAIL:-admin@example.com}"
      DJ_SUDO_PASSWORD: "${UM_DJ_SUDO_PASSWORD:-transcendence}"
    depends_on:
      db_usermanagement:
        condition: service_healthy
    restart: on-failure
    networks:
      - network_user_management
      - network_django
    secrets:
      - public_key.pem
      - private_key.pem # TODO: !!! delete this line
