POST {{base_url}}/registration/basic_signup
Content-Type: application/json

{
    "username": "{{username3}}",
    "password": "{{current_password3}}"
}

###

# @name signup
POST {{base_url}}/registration/basic_signup
Content-Type: application/json

{
    "username": "{{username3}}",
    "password": "{{current_password3}}",
    "otp": "0000000000000000"
}

###

@CODE0 = {{signup.response.body.backup_codes.0}}
@CODE1 = {{signup.response.body.backup_codes.1}}
@CODE2 = {{signup.response.body.backup_codes.2}}
@CODE3 = {{signup.response.body.backup_codes.3}}
@CODE4 = {{signup.response.body.backup_codes.4}}

###

POST {{base_url}}/registration/backup_login
Content-Type: application/json

{
    "username": "{{username3}}",
    "password": "{{current_password3}}",
    "backup_code": "notcorrect1234"

}

###

POST {{base_url}}/registration/backup_login
Content-Type: application/json

{
    "username": "{{username3}}",
    "password": "wrongpassword",
    "backup_code": "{{CODE1}}"

}

###

POST {{base_url}}/registration/backup_login
Content-Type: application/json

{
    "username": "{{username3}}",
    "password": "{{current_password3}}"
}

###

POST {{base_url}}/registration/backup_login
Content-Type: application/json

{
    "username": "{{username3}}",
    "backup_code": "{{CODE1}}"
}
###

POST {{base_url}}/registration/backup_login
Content-Type: application/json

{
    "username": "{{username3}}",
    "password": "{{current_password3}}",
    "backup_code": "{{CODE2}}"
}
