POST {{base_url}}/registration/basic_signup
Content-Type: application/json

{
    "username": "{{username3}}",
    "password": "{{current_password3}}"
}

###

# @name signup1
POST {{base_url}}/registration/basic_signup
Content-Type: application/json

{
    "username": "{{username3}}",
    "password": "{{current_password3}}",
    "otp": "0000000000000000"
}

###

@CODEA0 = {{signup1.response.body.backup_code.0}}
@CODEA1 = {{signup1.response.body.backup_code.1}}
###

# @name backup_login1
POST {{base_url}}/registration/backup_login
Content-Type: application/json

{
    "username": "{{username3}}",
    "backup_code": "{{CODEA0}}"
}

###
@ACCESS_COOKIE = {{backup_login1.response.headers.Set-Cookie}};
###
# @name rotate1
POST {{base_url}}/registration/backup_rotate_codes
Content-Type: application/json
Cookie: {{ACCESS_COOKIE}}

{
    "username": "{{username3}}",
    "password": "{{current_password3}}"
}

###
@CODEB0 = {{rotate1.response.body.backup_code.0}}
###

POST {{base_url}}/registration/backup_login
Content-Type: application/json
Cookie: {{ACCESS_COOKIE}}

{
    "username": "{{username3}}",
    "backup_code": "{{CODEA1}}"
}
###
POST {{base_url}}/registration/backup_login
Content-Type: application/json
Cookie: {{ACCESS_COOKIE}}

{
    "username": "{{username3}}",
    "backup_code": "{{CODEB0}}"
}