@first_otp = 61IWWWMPTYKB2FKI
@second_otp = 2MAF8LBMYD3PYQAQ 

POST {{base_url}}/registration/basic_signup
Content-Type: application/json

{
    "username": "{{username2-1}}",
    "password": "{{current_password2}}"
}

###

POST {{base_url}}/registration/basic_signup_change_username
Content-Type: application/json

{
    "current_username": "{{username2-1}}",
    "new_username": "{{username2-2}}"
}

###

POST {{base_url}}/registration/basic_signup
Content-Type: application/json

{
    "username": "{{username2-1}}",
    "password": "{{current_password2}}",
    "otp": "{{first_otp}}"
}

###

POST {{base_url}}/registration/basic_signup
Content-Type: application/json

{
    "username": "{{username2-1}}",
    "password": "{{current_password2}}",
    "otp": "{{second_otp}}"
}

###

POST {{base_url}}/registration/basic_signup
Content-Type: application/json

{
    "username": "{{username2-2}}",
    "password": "{{current_password2}}",
    "otp": "{{first_otp}}"
}

###

POST {{base_url}}/registration/basic_signup
Content-Type: application/json

{
    "username": "{{username2-2}}",
    "password": "{{current_password2}}",
    "otp": "{{second_otp}}"
}
