
POST {{base_url}}/registration/signup/
Content-Type: application/json

{
    "username": "{{username3}}",
    "password": "{{current_password3}}"
}

###

POST {{base_url}}/registration/basic_login/
Content-Type: application/json

{
    "username": "{{username3}}",
    "password": "{{current_password3}}"
}

###

POST {{base_url}}/registration/basic_login/
Content-Type: application/json

{
    "username": "{{username3}}",
    "password": "{{current_password3}}",
    "otp": "1E48F3779V92600V"
}

#######################################################################################

POST {{base_url}}/registration/basic_signup/
Content-Type: application/json

{
    "username": "{{username4}}",
    "password": "{{current_password4}}"
}

###

POST {{base_url}}/registration/basic_login/
Content-Type: application/json

{
    "username": "{{username4}}",
    "password": "{{current_password4}}"
}

###