# @name signup
POST {{base_url}}/registration/signup
Content-Type: application/json

{
    "username": "{{username5}}",
    "password": "{{current_password5}}"
}

###

@ACCESS_COOKIE = {{signup.response.headers.Set-Cookie}};

###

POST {{base_url}}/registration/change_password
Content-Type: application/json
Cookie: {{ACCESS_COOKIE}}

{
    "current_password": "{{current_password5}}",
    "new_password": "{{new_password5}}"
}

###

POST {{base_url}}/registration/change_password
Content-Type: application/json
Cookie: {{ACCESS_COOKIE}}

{
    "current_password": "{{current_password5}}",
    "new_password": "{{new_password5}}",
    "otp": "JE595BH5KIIW5ZBG"
}

###

POST {{base_url}}/registration/login
Content-Type: application/json

{
    "username": "{{username5}}",
    "password": "{{new_password5}}"
}