@otp = 0000000000000000 
POST {{base_url}}/registration/basic_signup
Content-Type: application/json

{
    "username": "{{username5}}",
    "password": "{{current_password5}}"
}


###

# @name signup
POST {{base_url}}/registration/basic_signup
Content-Type: application/json

{
    "username": "{{username5}}",
    "password": "{{current_password5}}",
    "otp": "{{otp}}"
}

###

@ACCESS_COOKIE1 = {{signup.response.headers.Set-Cookie}};

###

POST {{base_url}}/um/user-creation
Content-Type: application/json
Cookie: {{ACCESS_COOKIE1}}

{
    "displayname": "{{displayname5}}"
}

###

POST {{base_url}}/registration/delete_user
Content-Type: application/json
Cookie: {{ACCESS_COOKIE1}} 

{"password": "{{current_password5}}"}

###

POST {{base_url}}/registration/basic_login
Content-Type: application/json

{
    "username": "{{username5}}",
    "password": "{{current_password5}}"
}
###

# @name login
POST {{base_url}}/registration/basic_login
Content-Type: application/json

{
    "username": "{{username5}}",
    "password": "{{current_password5}}",
	"otp": "{{otp}}"
}

###

@ACCESS_COOKIE2 = {{login.response.headers.Set-Cookie}};

###

POST {{base_url}}/registration/delete_user
Content-Type: application/json
Cookie: {{ACCESS_COOKIE2}} 

{
    "password": "{{current_password5}}",
    "otp": "{{otp}}"
}

###

POST {{base_url}}/registration/basic_login
Content-Type: application/json

{
    "username": "{{username5}}",
    "password": "{{current_password5}}"
}

###