@otp = 0000000000000000 
POST {{base_url}}/registration/basic_signup
Content-Type: application/json

{
    "username": "{{username2-1}}",
    "password": "{{current_password2}}"
}

###
POST {{base_url}}/registration/basic_signup
Content-Type: application/json

{
    "username": "{{username2-1}}",
    "password": "{{current_password2}}",
    "otp": "{{otp}}"
}

###

POST {{base_url}}/registration/basic_forgot_password
Content-Type: application/json

{
    "username": "{{username2-1}}"
}

###

POST {{base_url}}/registration/basic_forgot_password
Content-Type: application/json

{
    "username": "{{username2-1}}",
    "otp": "{{otp}}",
    "new_password": "{{new_password2}}"
}

###

POST {{base_url}}/registration/basic_login
Content-Type: application/json

{
    "username": "{{username2-1}}",
    "password": "{{new_password2}}"
}

###

POST {{base_url}}/registration/basic_login
Content-Type: application/json

{
    "username": "{{username2-1}}",
    "password": "{{new_password2}}",
    "otp": "{{otp}}"
}