@base_url = https://localhost:8000

# @name post_signup
POST {{base_url}}/registration/signup
Content-Type: application/json

{"username": "email@domain.at", "password": "Pass1234!"}

###

# @name post_login
POST {{base_url}}/registration/login
Content-Type: application/json

{"username": "email@domain.at", "password": "Pass1234!"}

###

@SET_COOKIE = {{post_login.response.headers.Set-Cookie}}

@ACCESS_COOKIE = {{SET_COOKIE}}.split(';')[0]

###

# @name get_oauth2_authorization_request
GET {{base_url}}/registration/send_oauth2_authorization_request
Content-Type: application/json
Cookie: {{ACCESS_COOKIE}}

{}

###



###

POST {{base_url}}/registration/exchange_code_against_access_token/?code={{CODE}}
Content-Type: application/json
Cookie: {{ACCESS_COOKIE}}

{
    "code": "0d431be0d2d78145be62d95cbef6d143f06178e355e22201e25836c62398b88c"
}

###

GET {{base_url}}/registration/unset_oauth2/
Content-Type: application/json
Cookie: access=a,b,c refresh=x,y,z

{}

###

GET {{base_url}}/registration/login_oauth2/
Content-Type: application/json
Cookie: access=a,b,c refresh=x,y,z

{}

