@otp = 0000000000000000 
@password5 = K1sQ9
@password128 = Rf0pnMlMrkyMUp5wYkCqzjbxNczaRn2dRf0pnMlMrkyMUp5wYkCqzjbxNczaRn2dRf0pnMlMrkyMUp5wYkCqzjbxNczaRn2dRf0pnMlMrkyMUp5wYkCqzjbxNczaRn2d

@password120 = T5PHtwrM5g8sfRxy4UN2UlObYiuIMtNiT5PHtwrM5g8sfRxy4UN2UlObYiuIMtNiT5PHtwrM5g8sfRxy4UN2UlObYiuIMtNiT5PHtwrM5g8sfRxy4UN2UlOb


## SIGNUP WITH PASSWORD VALIDATORS
POST {{base_url}}/registration/basic_signup
Content-Type: application/json

{
    "username": "{{username3}}",
    "password": "abc"
}

###

POST {{base_url}}/registration/basic_signup
Content-Type: application/json

{
    "username": "{{username3}}",
    "password": "whatever"
}

###

POST {{base_url}}/registration/basic_signup
Content-Type: application/json

{
    "username": "{{username3}}",
    "password": "{{password5}}"
}

###

POST {{base_url}}/registration/basic_signup
Content-Type: application/json

{
    "username": "{{username3}}",
    "password": "{{password128}}"
}


###

POST {{base_url}}/registration/basic_signup
Content-Type: application/json

{
    "username": "{{username3}}",
    "password": "{{password120}}"
}

###

POST {{base_url}}/registration/basic_signup_change_password
Content-Type: application/json

{
    "username": "{{username3}}",
    "new_password": "abc"
}

###

POST {{base_url}}/registration/basic_signup_change_password
Content-Type: application/json

{
    "username": "{{username3}}",
    "new_password": "{{new_password2}}"
}

###



POST {{base_url}}/registration/basic_signup
Content-Type: application/json

{
    "username": "{{username3}}",
    "password": "{{new_password2}}",
    "otp": "{{otp}}"
}

###

POST {{base_url}}/registration/basic_login
Content-Type: application/json

{
    "username": "{{username3}}",
    "password": "{{new_password2}}"
}

###

POST {{base_url}}/registration/basic_login
Content-Type: application/json

{
    "username": "{{username3}}",
    "password": "{{new_password2}}",
    "otp": "{{otp}}"
}

###################################

## CHANGE PASSWORD WITH PASSWORD VALIDATORS

POST {{base_url}}/registration/basic_login
Content-Type: application/json

{
    "username": "{{username3}}",
    "password": "{{new_password2}}"
}

###

# @name login
POST {{base_url}}/registration/basic_login
Content-Type: application/json

{
    "username": "{{username3}}",
    "password": "{{new_password2}}",
    "otp": "{{otp}}"
}

###

@ACCESS_COOKIE = {{login.response.headers.Set-Cookie}};

###

POST {{base_url}}/registration/change_password
Content-Type: application/json
Cookie: {{ACCESS_COOKIE}}

{
    "current_password": "{{new_password2}}",
    "new_password": "whatever"
}

###

POST {{base_url}}/registration/change_password
Content-Type: application/json
Cookie: {{ACCESS_COOKIE}}

{
    "current_password": "{{new_password2}}",
    "new_password": "{{new_password5}}"
}

###

POST {{base_url}}/registration/change_password
Content-Type: application/json
Cookie: {{ACCESS_COOKIE}}

{
    "current_password": "{{new_password2}}",
    "new_password": "{{new_password5}}",
    "otp": "{{otp}}"
}

###

POST {{base_url}}/registration/basic_login
Content-Type: application/json

{
    "username": "{{username3}}",
    "password": "{{new_password5}}"
}

###

POST {{base_url}}/registration/basic_login
Content-Type: application/json

{
    "username": "{{username3}}",
    "password": "{{new_password5}}",
    "otp": "{{otp}}"
}

######################

## FORGOT_PASSWORD WITH PASSWORD VALIDATORS

POST {{base_url}}/registration/basic_forgot_password
Content-Type: application/json

{
    "username": "{{username3}}"
}

###

POST {{base_url}}/registration/basic_forgot_password
Content-Type: application/json

{
    "username": "{{username3}}",
    "new_password": "wrong",
    "otp": "{{otp}}"
}

###
POST {{base_url}}/registration/basic_forgot_password
Content-Type: application/json

{
    "username": "{{username3}}"
}

###

POST {{base_url}}/registration/basic_forgot_password
Content-Type: application/json

{
    "username": "{{username3}}",
    "new_password": "{{new_password2}}",
    "otp": "{{otp}}"
}

###

POST {{base_url}}/registration/basic_login
Content-Type: application/json

{
    "username": "{{username3}}",
    "password": "{{new_password2}}"
}

###

POST {{base_url}}/registration/basic_login
Content-Type: application/json

{
    "username": "{{username3}}",
    "password": "{{new_password2}}",
    "otp": "{{otp}}"
}
