
POST https://127.0.0.1:8000/registration/signup/
Content-Type: application/json

{"username": "email@domain.at", "password": "Pass1234!"}

###

POST https://127.0.0.1:8000/registration/login/
Content-Type: application/json

{"username": "email@domain.at", "password": "Pass1234!"}

###

POST https://127.0.0.1:8000/registration/delete_user/
Content-Type: application/json
Cookie: access=a,b,c refresh=x,y,z

{"current_password": "Pass1234!"}

###

GET https://127.0.0.1:8000/registration/logout/
Content-Type: application/json
Cookie: access=a,b,c refresh=x,y,z

{}

###

POST https://127.0.0.1:8000/registration/change_password/
Content-Type: application/json
Cookie: access=a,b,c refresh=x,y,z

{"current_password": "Pass1234!", "new_password": "Pass5678!"}

###

GET https://127.0.0.1:8000/registration/verify_token/
Content-Type: application/json
Cookie: access=a,b,c refresh=x,y,z

{}

###

GET https://127.0.0.1:8000/registration/refresh_token/
Content-Type: application/json
Cookie: access=a,b,c refresh=x,y,z

{}

###

GET https://127.0.0.1:8000/registration/get_oauth2_url/
Content-Type: application/json
Cookie: access=a,b,c refresh=x,y,z

{}

###

POST https://127.0.0.1:8000/registration/set_oauth2/
Content-Type: application/json
Cookie: access=a,b,c refresh=x,y,z

{}

###

GET https://127.0.0.1:8000/registration/unset_oauth2/
Content-Type: application/json
Cookie: access=a,b,c refresh=x,y,z

{}

###

GET https://127.0.0.1:8000/registration/login_oauth2/
Content-Type: application/json
Cookie: access=a,b,c refresh=x,y,z

{}