name: test compilation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:


jobs:
  make_rule_check:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/checkout@v4
    - name: generate keys
      run: make keys
    - name: Makefile check
      run: make build_only
    - name: start servers
      run: make &

    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: apt update and install python-dev, gcc and libmariadb-dev
      run: |
        sudo apt update
        sudo apt install gcc -y
        sudo apt-get install libmariadb-dev -y
        sudo apt-get install python3.10-dev -y

    - name: Install browser dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libwoff1 \
          libopus0 \
          libwebp6 \
          libwebpdemux2 \
          libenchant1c2a \
          libgudev-1.0-0 \
          libsecret-1-0 \
          libhyphen0 \
          libgstreamer-gl1.0-0 \
          libgstreamer-plugins-bad1.0-0 \
          libgstreamer-plugins-base1.0-0 \
          gstreamer1.0-libav \
          gstreamer1.0-plugins-bad \
          gstreamer1.0-plugins-base \
          gstreamer1.0-plugins-good \
          gstreamer1.0-plugins-ugly \
          gstreamer1.0-pulseaudio \
          libgstreamer1.0-0 \
          libharfbuzz-icu0 \
          libvpx6 \
          libevent-2.1-7 \
          libflite1 \
          libgles2

    - name: playwright install
      run: playwright install

    - name: playwright test
      run: pytest playwright_tests/test_basic.py
