name: test compilation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:


jobs:
  make_rule_check:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: generate keys
      run: make keys
    - name: Makefilecheck
      run: make &
    - name: Sleep for 30 seconds
      uses: jakejarvis/wait-action@master
      with:
        time: '10s'
