name: running tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:


jobs:
  build_start_test:
    runs-on: ubuntu-latest

    env: # Or as an environment variable
      EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
      EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD}}
      MOCK_EMAIL: ${{ vars.MOCK_EMAIL }}
        
    steps:
    - uses: actions/checkout@v4

    - name: generate keys
      run: make keys

    - name: Makefile check
      run: make build_only

    - name: start servers
      run: |
        make &
        while ! nc -z localhost 8443; do
          echo "Waiting for server ..."
          sleep 2
        done

    - name: run user_management api tests
      run: make um_test

    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('tests/playwright_tests/playwright_requirements.txt') }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r tests/playwright_tests/playwright_requirements.txt

    # do we even need the following run, python, mariadb?
    #- name: apt update and install python-dev, gcc and libmariadb-dev
    #  run: |
    #    sudo apt update
    #    sudo apt install gcc -y
    #    sudo apt-get install libmariadb-dev -y
    #    sudo apt-get install python3.10-dev -y

    - name: playwright install
      run: playwright install

    - name: playwright tests
      run: pytest ./tests/playwright_tests
