name: Prettier for FE (JS/HTML/CSS)

on:
  push:
    branches:
      - frontend
      - frontend/*
      - frontend/**
      - prettier-test

jobs:
  prettier:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Prettier Action
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write **/*.{js,css,html} --config linterrules/.prettierrc.json
          github_token: ${{ secrets.GITHUB_TOKEN }}
