name: Prettier for FE (JS/HTML/CSS)

on:
  push:
    branches:
      - frontend
      - frontend/michael
      - frontend/fiona
      - prettier-test

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install npm v8
        run: npm i -g npm@8

      - name: Prettier Action
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write **/*.{js,yaml,yml,css,html}
          github_token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}

